# This is a basic workflow to help you get started with Actions

name: python_application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install dependencies
      - name: Install Dependencies
        run: |
          pythom -m pip install --upgrade pip
          pip install black
          pip install pylint
          pip install pylint-exit

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pylint * --max-line-length=80 || pylint-exit $?
          if [ $? -ne 0 ]; then
            echo "An error occurred while running pylint." >&2
            exit 1
          fi
          black --check .
